apiVersion: v1
kind: Service
metadata:
  name: scheduling-service-front-service
spec:
  selector:
    app: scheduling-service-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
